config/routes.rb
IeRoRTagg::Application.routes.draw do
  devise_for :users
  
  resources :tutorials do
    post 'up' => 'rankings#up', as: 'up'
    post 'down' => 'rankings#down', as: 'down'
  end
  resources :users
  root to: 'tutorials#index'

end

app/models/ranking.rb
class Ranking < ActiveRecord::Base
  attr_accessible :tutorial_id, :user_id, :vote

  validates_numericality_of :vote, only_integer: true, less_than_or_equal_to: 1, greater_than_or_equal_to: -1

  belongs_to :user
  belongs_to :tutorial

  after_create :update_cached_rating

  private
    def update_cached_rating
      tutorial.cached_rating += vote
      tutorial.save
    end
end

app/models/tutorial.rb
class Tutorial < ActiveRecord::Base
  default_scope order "cached_rating DESC"

  attr_accessible :link, :name
  
  belongs_to :user
  has_many :rankings
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  attr_accessible :email, :username

  has_many :tutorials
  has_many :rankings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/rankings_controller.rb
class RankingsController < ApplicationController
  def up
    @tutorial = Tutorial.find params[:tutorial_id]
    unless (ranking = @tutorial.rankings.find_by_user_id(current_user.id)).nil?
      if ranking.vote == 1
        redirect_to root_path 
        return
      end
      ranking.delete
      @tutorial.update_attribute :cached_rating, (@tutorial.cached_rating + 1)
    end
    @tutorial.rankings.create vote: 1, user_id: current_user.id
    redirect_to root_path
  end

  def down
    @tutorial = Tutorial.find params[:tutorial_id]
    unless (ranking = @tutorial.rankings.find_by_user_id(current_user.id)).nil?
      if ranking.vote == -1
        redirect_to root_path 
        return
      end
      ranking.delete
      @tutorial.update_attribute :cached_rating, (@tutorial.cached_rating - 1)
    end
    @tutorial.rankings.create vote: -1, user_id: current_user.id
    redirect_to root_path
  end
end

app/controllers/tutorials_controller.rb
class TutorialsController < ApplicationController
  def new
    @tutorial = current_user.tutorials.new
  end

  def show
    @tutorial = Tutorial.find_by_id params[:id]
  end

  def edit
    @tutorial = Tutorial.find_by_id params[:id]
  end

  def index
    @tutorials= Tutorial.all
  end

  def create
    @tutorial = current_user.tutorials.build params[:tutorial]
    if @tutorial.save
      redirect_to @tutorial
    else
      render 'new'
    end
  end

  def destroy
    @tutorial= Tutorial.find_by_id params[:id]
    @tutorial.delete
    redirect_to root_path
  end

  def update
    @tutorial = Tutorial.find_by_id params[:id]
    if @tutorial.update_attributes params[:tutorial]
      redirect_to @tutorial
    else
      render 'new'
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
    @tutorials = @user.tutorials
  end

  def create
    @user = User.create(params[:user])
    if @user.save
      redirect_to @user
    else
      render 'new'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ranking_helper.rb
module RankingHelper
end

app/helpers/tutorials_helper.rb
module TutorialsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "IeRoRTagg" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'images/favicon.ico', :rel => 'shortcut icon' %>
  </head>
  <body>

    <div class="navbar">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <%= link_to "IeRoRTagg", root_path, class: "brand" %>
          <div class="container nav-collapse">
            <ul class="nav">
              <% if user_signed_in? %>
                <li><%= link_to "Add a Tutorial", new_tutorial_path  %></li>
                <li><%= link_to "Logout", destroy_user_session_path, method: :delete  %></li>
              <% else %>
                <li><%= link_to "Add a Tutorial", new_tutorial_path  %></li>
                <li><%= link_to "Sign Up", new_user_registration_path %></li>
                <li><%= link_to "Login", new_user_session_path %>
              <% end %>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
        <div class="row">
          <div class="span9">
            <% flash.each do |name, msg| %>
              <% if msg.is_a?(String) %>
                <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
                  <a class="close" data-dismiss="alert">&#215;</a>
                  <%= content_tag :div, msg, :id => "flash_#{name}" %>
                </div>
              <% end %>
            <% end %>
            <%= yield %>
          </div>
          <div class="span3">
            <div class="well sidebar-nav">
              <h3>Sidebar</h3>
              <ul class="nav nav-list">
                <li class="nav-header">Sidebar</li>
                <li><%= link_to "Link1", "/path1"  %></li>
                <li><%= link_to "Link2", "/path2"  %></li>
                <li><%= link_to "Link3", "/path3"  %></li>
              </ul>
            </div><!--/.well -->
          </div><!--/span-->
        </div><!--/row-->

      <footer>
        <p>&copy; Company 2012</p>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/tutorials/_form.html.erb
<%= form_for @tutorial, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :link, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :link, :class => 'text_field' %>
    </div>
  </div>
  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                root_path, :class => 'btn' %>
  </div>
<% end %>

app/views/tutorials/all.html.erb
<%- model_class = Tutorial -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:link) %></th>
      <th><%= model_class.human_attribute_name(:cached_rating) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @tutorials.each do |tutorial| %>
      <tr>
        <td><%= link_to tutorial.id, tutorial_path(tutorial) %></td>
        <td><%= tutorial.name %></td>
        <td><%= tutorial.link %></td>
        <td><%= tutorial.cached_rating %></td>
        <td><%=l tutorial.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_tutorial_path(tutorial), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      tutorial_path(tutorial),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_tutorial_path,
            :class => 'btn btn-primary' %>

app/views/tutorials/create.html.erb
<h1>Tutorials#create</h1>
<p>Find me in app/views/tutorials/create.html.erb</p>

app/views/tutorials/edit.html.erb
<%- model_class = Tutorial -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/tutorials/index.html.erb
<%- model_class = Tutorial -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:link) %></th>
      <th>Rating</th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @tutorials.each do |tutorial| %>
      <tr>
        <td><%= link_to tutorial.name, tutorial %></td>
        <td><%= tutorial.link %></td>
        <td><%= tutorial.cached_rating %></td>
        <td>
          <% if user_signed_in? and current_user == tutorial.user %>
            <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_tutorial_path(tutorial), :class => 'btn btn-mini' %>
            <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      tutorial_path(tutorial),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
          <% elsif user_signed_in? %>
            <%= link_to image_tag('up_arrow.png'), tutorial_up_path(tutorial.id), method: 'post' %>
            <%= link_to image_tag('down_arrow.png'), tutorial_down_path(tutorial.id), method: 'post' %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<% if user_signed_in? %>
  <%= link_to t('.new', :default => t("helpers.links.new")),
            new_tutorial_path,
            :class => 'btn btn-primary' %>
<% end %>

app/views/tutorials/new.html.erb
<%- model_class = Tutorial -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/tutorials/show.html.erb
<div class="page-header">
  <h1><%=t '.title', :default => Tutorial.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= Tutorial.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @tutorial.name %></dd>
  <dt><strong><%= Tutorial.human_attribute_name(:link) %>:</strong></dt>
  <dd><%= @tutorial.link %></dd>
  <dt><strong><%= Tutorial.human_attribute_name(:cached_rating) %>: </strong></dt>
  <dd><%= @tutorial.cached_rating %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              root_path, :class => 'btn'  %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              tutorial_path(@tutorial),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/users/_form.html.erb
<%= form_for @user, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :username, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :username, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :email, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :email, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                users_path, :class => 'btn' %>
  </div>
<% end %>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/edit.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/users/new.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/users/show.html.erb
<div class="page-header">
  <h1><%=t '.title', :default => User.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= User.human_attribute_name(:username) %>:</strong></dt>
  <dd><%= @user.username %></dd>
  <dt><strong><%= User.human_attribute_name(:email) %>:</strong></dt>
  <dd><%= @user.email %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              root_path, :class => 'btn'  %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              user_path(@user),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>
<div class="page-header">
  <h1><%=t '.title', :default => "Tutorial".pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= Tutorial.human_attribute_name(:id) %></th>
      <th><%= Tutorial.human_attribute_name(:name) %></th>
      <th><%= Tutorial.human_attribute_name(:link) %></th>
      <th><%= Tutorial.human_attribute_name(:cached_rating) %></th>
      <th><%= Tutorial.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @tutorials.each do |tutorial| %>
      <tr>
        <td><%= link_to tutorial.id, tutorial_path(tutorial) %></td>
        <td><%= tutorial.name %></td>
        <td><%= tutorial.link %></td>
        <td><%= tutorial.cached_rating %></td>
        <td><%=l tutorial.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_tutorial_path(tutorial), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      tutorial_path(tutorial),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_tutorial_path,
            :class => 'btn btn-primary' %>